[package]
name = "server"
version = "0.1.0"
authors = ["Chris Conley <pair+chris@realscout.com>"]
[lib]
name = "avr"
path = "src/lib.rs"
[[bin]]
name = "server"
path = "src/main.rs"
[dependencies]
websocket = "~0.12.2"
rustc-serialize = "0.3"
bit-vec = "0.4.0"
